### ISSUE TITLE
Error Leaving Bounding Box

### ISSUE THREAD

**Issue by LordNex** [Tyrsis/BlueprintPlugin#48]
I believe this came up when I remote flew a ship out of a bounding box shipyard

2014-12-12 16:45:14.597 - Thread:   5 ->  Exception occured: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at hkpWorld.addConstraint(hkpWorld* , hkpConstraintInstance* )
   at Havok.HkWorld.AddConstraint(HkConstraint constraint)
   at D1B6432AAEEF40F9D99F69835A7B23F5.5BAA908D4615EC702E28985E09DBEF8F.3D78C75E1CD88E9A2FDCF37C01996129()
   at VRageMath.Spatial.MyClusterTree.ReorderClusters(BoundingBoxD aabb, UInt64 objectId)
   at VRageMath.Spatial.MyClusterTree.MoveObject(UInt64 id, BoundingBoxD oldAabb, BoundingBoxD aabb, Vector3 velocity)
   at D1B6432AAEEF40F9D99F69835A7B23F5.5BAA908D4615EC702E28985E09DBEF8F.1CFEE835C0D978E0A4BB22EE7C913B35()
   at D1B6432AAEEF40F9D99F69835A7B23F5.5BAA908D4615EC702E28985E09DBEF8F.5D6AC5263DFBFD7144649F69EDC131DF(HkRigidBody EEA498F59527FDBA65C3CBD38F5B4BDA, Single 970FFFAF46A39806418737C3E522563D)
   at D1B6432AAEEF40F9D99F69835A7B23F5.553E5847558E9D51837A1071E2207F67.Simulate()
   at AAC05F537A6F0F6775339593FBDFC564.D580AE7552E79DAB03A3D64B1F7B67F9.F672BBF9E192151CE8FD7E91E62B997D()
   at AAC05F537A6F0F6775339593FBDFC564.D580AE7552E79DAB03A3D64B1F7B67F9.EC90B1C44E3C361983D093F355FF0CC8(MyTimeSpan 9916A9BA14FB0BB1A36908E2E8C15A74)
   at B337879D0C82A5F9C44D51D954769590.B3531963E948FB4FA1D057C4340C61B4.5A1BD5F986D831B0FAAF25627B3ED093()
   at 168638249D29224100DB50BB468E7C07.7BAD4AFD06B91BCD63EA57F7C0D4F408.2457E95BE2F0D1F1A4A009B2B1DBBDA4()
   at 168638249D29224100DB50BB468E7C07.398AD1E315E6E4D570C424BD0D168FC1.858DA51EB20785A82D9A03614304088A.0187A29A24275EC024A192E7E235CC2E.9C41E76459B99591F991CBA0833BD17E()
   at 168638249D29224100DB50BB468E7C07.6E0E814918D8AD6B2DC9CA5005102256.8410AF4CE140B7AF0C656E2077FA7678(9AA159E6C22F64A542015EED199D04B9 148A5BA193EB90E55F5E805EF96CAD48)
   at 168638249D29224100DB50BB468E7C07.398AD1E315E6E4D570C424BD0D168FC1.8410AF4CE140B7AF0C656E2077FA7678(9AA159E6C22F64A542015EED199D04B9 148A5BA193EB90E55F5E805EF96CAD48)
   at B337879D0C82A5F9C44D51D954769590.B3531963E948FB4FA1D057C4340C61B4.246E732EE67F7F6F88C4FF63B3901107(Boolean FF8E4184144DE7049FF5EC07D594DAB6, Action 8CF1B812E214DD1C51DD894D4C05D44A)
   at 83BCBFA49B3A2A6EC1BC99583DA2D399.49BCFF86BA276A9C7C0D269C2924DE2D.523C8831DA5DAB3A19F6D33A2C6437B5()
   at 83BCBFA49B3A2A6EC1BC99583DA2D399.49BCFF86BA276A9C7C0D269C2924DE2D.26A7ABEA729FAE1F24679E21470F8E98(String 8BF03A34188889479CB413E58490FC37, String 48C45E39212AAA2B19C972DA9195F48A, Boolean 7AC487C1B445CD9F481CF5FE695A7CEA, Boolean 4292A7A4DACAF323E558B7E11DD3CF00)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at SEModAPIInternal.API.Server.ServerAssemblyWrapper.StartServer(String instanceName, String overridePath, Boolean useConsole)
   at SEModAPIExtensions.API.Server.RunServer()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
2014-12-12 16:45:14.597 - Thread:   5 ->  InnerException: 
2014-12-12 16:45:14.597 - Thread:   5 ->  Exception occured: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at hkpWorld.addConstraint(hkpWorld* , hkpConstraintInstance* )
   at Havok.HkWorld.AddConstraint(HkConstraint constraint)
   at D1B6432AAEEF40F9D99F69835A7B23F5.5BAA908D4615EC702E28985E09DBEF8F.3D78C75E1CD88E9A2FDCF37C01996129()
   at VRageMath.Spatial.MyClusterTree.ReorderClusters(BoundingBoxD aabb, UInt64 objectId)
   at VRageMath.Spatial.MyClusterTree.MoveObject(UInt64 id, BoundingBoxD oldAabb, BoundingBoxD aabb, Vector3 velocity)
   at D1B6432AAEEF40F9D99F69835A7B23F5.5BAA908D4615EC702E28985E09DBEF8F.1CFEE835C0D978E0A4BB22EE7C913B35()
   at D1B6432AAEEF40F9D99F69835A7B23F5.5BAA908D4615EC702E28985E09DBEF8F.5D6AC5263DFBFD7144649F69EDC131DF(HkRigidBody EEA498F59527FDBA65C3CBD38F5B4BDA, Single 970FFFAF46A39806418737C3E522563D)
   at D1B6432AAEEF40F9D99F69835A7B23F5.553E5847558E9D51837A1071E2207F67.Simulate()
   at AAC05F537A6F0F6775339593FBDFC564.D580AE7552E79DAB03A3D64B1F7B67F9.F672BBF9E192151CE8FD7E91E62B997D()
   at AAC05F537A6F0F6775339593FBDFC564.D580AE7552E79DAB03A3D64B1F7B67F9.EC90B1C44E3C361983D093F355FF0CC8(MyTimeSpan 9916A9BA14FB0BB1A36908E2E8C15A74)
   at B337879D0C82A5F9C44D51D954769590.B3531963E948FB4FA1D057C4340C61B4.5A1BD5F986D831B0FAAF25627B3ED093()
   at 168638249D29224100DB50BB468E7C07.7BAD4AFD06B91BCD63EA57F7C0D4F408.2457E95BE2F0D1F1A4A009B2B1DBBDA4()
   at 168638249D29224100DB50BB468E7C07.398AD1E315E6E4D570C424BD0D168FC1.858DA51EB20785A82D9A03614304088A.0187A29A24275EC024A192E7E235CC2E.9C41E76459B99591F991CBA0833BD17E()
   at 168638249D29224100DB50BB468E7C07.6E0E814918D8AD6B2DC9CA5005102256.8410AF4CE140B7AF0C656E2077FA7678(9AA159E6C22F64A542015EED199D04B9 148A5BA193EB90E55F5E805EF96CAD48)
   at 168638249D29224100DB50BB468E7C07.398AD1E315E6E4D570C424BD0D168FC1.8410AF4CE140B7AF0C656E2077FA7678(9AA159E6C22F64A542015EED199D04B9 148A5BA193EB90E55F5E805EF96CAD48)
   at B337879D0C82A5F9C44D51D954769590.B3531963E948FB4FA1D057C4340C61B4.246E732EE67F7F6F88C4FF63B3901107(Boolean FF8E4184144DE7049FF5EC07D594DAB6, Action 8CF1B812E214DD1C51DD894D4C05D44A)
   at 83BCBFA49B3A2A6EC1BC99583DA2D399.49BCFF86BA276A9C7C0D269C2924DE2D.523C8831DA5DAB3A19F6D33A2C6437B5()
   at 83BCBFA49B3A2A6EC1BC99583DA2D399.49BCFF86BA276A9C7C0D269C2924DE2D.26A7ABEA729FAE1F24679E21470F8E98(String 8BF03A34188889479CB413E58490FC37, String 48C45E39212AAA2B19C972DA9195F48A, Boolean 7AC487C1B445CD9F481CF5FE695A7CEA, Boolean 4292A7A4DACAF323E558B7E11DD3CF00)
2014-12-12 16:45:14.598 - Thread:   5 ->  Hiding window
2014-12-12 16:45:14.811 - Thread:   5 ->  Network readers disposed
2014-12-12 16:45:14.811 - Thread:   5 ->  Logging off Steam...
2014-12-12 16:45:14.811 - Thread:   5 ->  Shutting down server...
2014-12-12 16:45:14.842 - Thread:   5 ->  Done
2014-12-12 16:45:14.858 - Thread:   5 ->  Hiding window done
2014-12-12 16:45:14.858 - Thread:   5 ->  Showing message

**Comment by LordNex** [comment]
aint seen it in a while
